// <auto-generated />
using System;
using Database_School_Project_.NET23_SQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database_School_Project_.NET23_SQL.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20231222083257_sp-GetStudentInfoId")]
    partial class spGetStudentInfoId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FkStudenNumber")
                        .HasColumnType("int")
                        .HasColumnName("FK_StudenNumber");

                    b.Property<int?>("FkWorkerNumber")
                        .HasColumnType("int")
                        .HasColumnName("FK_WorkerNumber");

                    b.HasKey("ClassId");

                    b.HasIndex("FkStudenNumber");

                    b.HasIndex("FkWorkerNumber");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseGradeSet")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CourseGradeSetDate")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("CourseName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FkStudenNumber")
                        .HasColumnType("int")
                        .HasColumnName("FK_StudenNumber");

                    b.Property<int?>("FkWorkerNumber")
                        .HasColumnType("int")
                        .HasColumnName("FK_WorkerNumber");

                    b.HasKey("CourseId")
                        .HasName("PK_Grade");

                    b.HasIndex("FkStudenNumber");

                    b.HasIndex("FkWorkerNumber");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Department", b =>
                {
                    b.Property<string>("DeparmentName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("DepartmentSalary")
                        .HasColumnType("int");

                    b.Property<int?>("FkWorkerNumber")
                        .HasColumnType("int")
                        .HasColumnName("FK_WorkerNumber");

                    b.HasIndex("FkWorkerNumber");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.SecretStudent", b =>
                {
                    b.Property<string>("StudentBirthDate")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentNumber"));

                    b.ToTable("SecretStudents");
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentNumber"));

                    b.Property<int?>("StudentAge")
                        .HasColumnType("int");

                    b.Property<string>("StudentBirthDate")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentGender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students", t =>
                        {
                            t.HasTrigger("TR_FindAge");

                            t.HasTrigger("TR_FindGender");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Worker", b =>
                {
                    b.Property<int>("WorkerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerNumber"));

                    b.Property<string>("WorkerBirthDate")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("WorkerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WorkerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WorkerProfession")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("WorkerStartDate")
                        .HasColumnType("date");

                    b.HasKey("WorkerNumber")
                        .HasName("PK_Person");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Class", b =>
                {
                    b.HasOne("Database_School_Project_.NET23_SQL.Models.Student", "FkStudenNumberNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("FkStudenNumber")
                        .HasConstraintName("FK_Class_Students");

                    b.HasOne("Database_School_Project_.NET23_SQL.Models.Worker", "FkWorkerNumberNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("FkWorkerNumber")
                        .HasConstraintName("FK_Class_Workers");

                    b.Navigation("FkStudenNumberNavigation");

                    b.Navigation("FkWorkerNumberNavigation");
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Course", b =>
                {
                    b.HasOne("Database_School_Project_.NET23_SQL.Models.Student", "FkStudenNumberNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("FkStudenNumber")
                        .HasConstraintName("FK_Grade_Students");

                    b.HasOne("Database_School_Project_.NET23_SQL.Models.Worker", "FkWorkerNumberNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("FkWorkerNumber")
                        .HasConstraintName("FK_Grade_Workers");

                    b.Navigation("FkStudenNumberNavigation");

                    b.Navigation("FkWorkerNumberNavigation");
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Department", b =>
                {
                    b.HasOne("Database_School_Project_.NET23_SQL.Models.Worker", "FkWorkerNumberNavigation")
                        .WithMany()
                        .HasForeignKey("FkWorkerNumber")
                        .HasConstraintName("FK_Department_Workers");

                    b.Navigation("FkWorkerNumberNavigation");
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Student", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Database_School_Project_.NET23_SQL.Models.Worker", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
